# Numpy Tricks

In [1]:
import numpy as np

In [3]:
np.version.version

'1.20.1'

In [4]:
mylist=[1,2,3]
mylist

[1, 2, 3]

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
my_matrices=[[1,3],[4,6]]
my_matrices

[[1, 3], [4, 6]]

In [7]:
np.array(my_matrices)

array([[1, 3],
       [4, 6]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(20,25)

array([20, 21, 22, 23, 24])

In [10]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.arange(30,15,-3)

array([30, 27, 24, 21, 18])

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(2,20,10)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [19]:
np.linspace(3,6,2)

array([3., 6.])

In [20]:
np.linspace(2,5,2)

array([2., 5.])

In [21]:
np.linspace(2,5,1)

array([2.])

In [22]:
np.linspace(0,77,100)

array([ 0.        ,  0.77777778,  1.55555556,  2.33333333,  3.11111111,
        3.88888889,  4.66666667,  5.44444444,  6.22222222,  7.        ,
        7.77777778,  8.55555556,  9.33333333, 10.11111111, 10.88888889,
       11.66666667, 12.44444444, 13.22222222, 14.        , 14.77777778,
       15.55555556, 16.33333333, 17.11111111, 17.88888889, 18.66666667,
       19.44444444, 20.22222222, 21.        , 21.77777778, 22.55555556,
       23.33333333, 24.11111111, 24.88888889, 25.66666667, 26.44444444,
       27.22222222, 28.        , 28.77777778, 29.55555556, 30.33333333,
       31.11111111, 31.88888889, 32.66666667, 33.44444444, 34.22222222,
       35.        , 35.77777778, 36.55555556, 37.33333333, 38.11111111,
       38.88888889, 39.66666667, 40.44444444, 41.22222222, 42.        ,
       42.77777778, 43.55555556, 44.33333333, 45.11111111, 45.88888889,
       46.66666667, 47.44444444, 48.22222222, 49.        , 49.77777778,
       50.55555556, 51.33333333, 52.11111111, 52.88888889, 53.66

In [23]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [26]:
np.random.rand(2)

array([0.49608688, 0.11047537])

In [27]:
np.random.rand(4,2)

array([[0.75795772, 0.03782103],
       [0.79981381, 0.82076911],
       [0.45068956, 0.20376825],
       [0.07220626, 0.23435204]])

In [3]:
np.random.randn(5)

array([ 0.21503361,  0.34591399, -0.09003601,  0.11095621, -1.20769805])

In [4]:
np.random.randn(5,5)

array([[ 1.85996989,  0.5255878 ,  1.14290197,  2.07814943,  0.33479257],
       [ 0.98251448,  0.847653  ,  1.65915434, -1.07877898, -1.08170495],
       [-0.81857319, -1.25110681, -1.1202479 , -1.32526314, -0.51603064],
       [ 1.74176962,  1.99391834, -0.84411001,  0.49446508,  1.35140098],
       [ 0.27539091, -0.86182421, -0.75855322,  0.08578958, -0.09179288]])

In [6]:
np.random.randint(5)

4

In [8]:
np.random.randint(2,3)

2

In [9]:
arr=np.arange(25)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
arr.shape

(25,)

In [12]:
b=arr.reshape(5,5)

In [13]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
arr.min()

0

In [15]:
arr.max()

24

In [19]:
randar=np.random.randint(0,50,20)

In [20]:
randar

array([43,  8,  3,  5, 44, 14, 34, 24, 46, 21,  2, 33,  3, 39, 12, 33,  6,
       41, 39, 41])

In [21]:
randar.min()

2

In [22]:
randar.argmin()

10

In [23]:
randar.argmax()

8

In [24]:
randarr1=np.random.randint(10,20,10)

In [25]:
randarr1

array([16, 19, 14, 11, 11, 14, 10, 16, 14, 14])

In [26]:
randarr1.min()

10

In [27]:
randarr1.max()

19

In [28]:
randarr1.argmin()

6

In [29]:
randarr1.argmax()

1

In [31]:
randarr1[2]

14

In [32]:
randarr1[1:5]

array([19, 14, 11, 11])

In [33]:
randarr1[:]

array([16, 19, 14, 11, 11, 14, 10, 16, 14, 14])

In [35]:
randarr1.shape

(10,)

In [39]:
randarr1.reshape(2,5)

array([[16, 19, 14, 11, 11],
       [14, 10, 16, 14, 14]])

In [42]:
new_arr=randarr1[1:7]

In [43]:
new_arr

array([19, 14, 11, 11, 14, 10])

In [44]:
new_arr[2:4]=17

In [45]:
new_arr

array([19, 14, 17, 17, 14, 10])

In [46]:
randarr1

array([16, 19, 14, 17, 17, 14, 10, 16, 14, 14])

In [47]:
b=randarr1.copy()
b

array([16, 19, 14, 17, 17, 14, 10, 16, 14, 14])

In [48]:
new_arr1=b[2:8]

In [49]:
new_arr1

array([14, 17, 17, 14, 10, 16])

In [50]:
new_arr1[1:3]=3

In [51]:
new_arr1

array([14,  3,  3, 14, 10, 16])

In [52]:
b

array([16, 19, 14,  3,  3, 14, 10, 16, 14, 14])

In [53]:
randarr1

array([16, 19, 14, 17, 17, 14, 10, 16, 14, 14])

In [54]:
b[1:3]=2

In [55]:
b

array([16,  2,  2,  3,  3, 14, 10, 16, 14, 14])

In [56]:
randarr1

array([16, 19, 14, 17, 17, 14, 10, 16, 14, 14])

In [58]:
arr_2d=np.array([[1,2,3],[4,5,6],[9,10,11]])

In [59]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11]])

In [60]:
arr_2d[2]

array([ 9, 10, 11])

In [61]:
arr_2d[0,1]

2

In [62]:
arr_2d[0][1]

2

In [63]:
arr_2d[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr_2d[[0,1],[1]]

array([2, 5])

In [65]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [66]:
arr_2d[2,:]

array([ 9, 10, 11])

In [67]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11]])

In [68]:
arr_2d>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [69]:
arr_2d<7

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [70]:
arr_2d[arr_2d>4]

array([ 5,  6,  9, 10, 11])

In [71]:
arr_2d+arr_2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [18, 20, 22]])

In [72]:

arr_2d/arr_2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
arr_2d*arr_2d

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 81, 100, 121]])

In [74]:
a=np.array([[1,2],[2,3]])
a

array([[1, 2],
       [2, 3]])

In [75]:
b=np.array([3,4])
b

array([3, 4])

In [76]:
np.matmul(b,a)

array([11, 18])

In [77]:
np.dot(arr_2d,arr_2d)

array([[ 36,  42,  48],
       [ 78,  93, 108],
       [148, 178, 208]])

In [78]:
list(b)

[3, 4]

In [79]:
b.tolist()

[3, 4]

In [83]:
tuple(b)

(3, 4)

In [85]:
arr_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 11]])

In [86]:
np.transpose(arr_2d)

array([[ 1,  4,  9],
       [ 2,  5, 10],
       [ 3,  6, 11]])